# Generated by Django 6.0.3 on 2026-03-30 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='description',
        ),
        migrations.AddField(
            model_name='student',
            name='student_id',
            field=models.CharField(default=1, max_length=50, unique=True),
        ),
    ]
